hl.unbind("CTRL + SUPER + T")
hl.unbind("SUPER + Super_L")
hl.unbind("SUPER + Super_R")
hl.unbind("SUPER + I")
hl.unbind("SUPER + V")
hl.unbind("SUPER + Period")
hl.unbind("SUPER + C")
hl.unbind("SUPER + X")
hl.unbind("SUPER + Tab")
hl.unbind("SUPER + A")
